### PR TITLE
Fixed some bugs and added support for reading a file of codes

### PR DESCRIPTION
**Pull request by ryparker**
I appreciated the ground work you put into this. This is my first time visiting typescript land but it was fun. I'd like to add a GUI or something to make it more accessible.

Anyways, here's what I added:
- Added `tsconfig` file so that my typescript knows what ECMAscript to use
- The secret directory was `.gitignored` so I made sure to create if it does not already exist
- Added a feature to allow reading codes from a `.txt` located in `/shiftcodes`
- Added a few of my own shiftcode text files (I don't think gearbox will care since I found them online anyways)
- Updated README

Known bugs:
- Now that we are speeding up the time that requests are made, the webservice tends to give up after 10 or so consecutive calls (response codes: 429/504). I've attempted to avoid this by adding a timeout after each request of about 10 seconds but results have not been consistent.

### CODE REVIEW

**Comment by sliekens** [comment]
Hey thanks for the PR! It's rather large so I'll cherry-pick the parts that are good to go and then get back to you.

**Comment by sliekens** [comment]
My notes so far:
- tsconfig was accidentally gitignored; I fixed that and pushed the config I used
- I added mkdir to the login command

I still have to think about how I want to support redeeming a list of codes. My original intention was to keep the CLI limited to "login" and "redeem 1 code". You could use a scripting language like bash to automate redeeming codes.

```bash
$input = "shiftcodes.txt"
$user = "john@doe.com"
while read code
    do shiftup redeem $user $code
done < $input
```

My other concern is about having codes in source control. I don't intend to update the lists myself so they probably wouldn't get updated often. 

My plan for now is to add retries to the "redeem" command when it sees a 429 response or exit gracefully when it sees a 504 response.

**Comment by ryparker** [comment]
Hey thanks for reviewing. I agree with most of your notes. Maintaining keys in the source control would be a burden. My goal was to let the application run for three minutes and redeem every code available. I wrote most of that code before testing if the redemption process would allow several requests in quick succession. It does not. 😅

I was expecting that with Borderlands 3 coming out, they would refresh the shift code system. However my hope of them removing the redemption limit did not come to fruition.

They refreshed the shift site and the redeeming process seems to have changed.
Here is the new order to redeem:
1. https://shift.gearboxsoftware.com/entitlement_offer_codes?code= 
2. https://shift.gearboxsoftware.com/code_redemptions
3. https://shift.gearboxsoftware.com/rewards

The timeout and the three code limit seems to remain the same. Also the exception handling has seemed to have gotten worse.

Sorry to be the bearer of bad news. I plan to look into the redemption process this weekend. It shouldn't be too difficult to update. I'll probably just close this PR and rebase from your latest.

It's inevitable that an increase of shift code interest will come with the release of Borderlands 3. Maybe it would be more beneficial to make this app more accessible? I appreciated this repo because entering codes on my Xbox is a pain. The site is alright but I'd like to be able to redeem all the key codes programmatically in a short period of time. There might be a way around the redemption limit but I'd need to dig into it this weekend. 

Sorry this got a bit lengthy.

**Comment by sliekens** [comment]
Thanks for all the research. I'll create issues to track the work that needs to be done. I still want to improve support for lists of codes, but I also want to make sure we get it right. Timeouts and rate limiting can be handled with retries and back-off algorithms. I'm not sure what to do about the redemption limit.

**Pull request closed without merging**
